### ISSUE TITLE
Alternative implementation suggestion

### ISSUE THREAD

**Issue by pygy** [hjylewis/trashable#5]
Hi @hjylewis implementing Thrashable as follows should be both faster and smaller.

The current implementation allocates two promises unconditionally whereas this one only creates a second one when the original promise is resolved, if the user called `thrash()`.

```JS
function makeTrashable(promise) {
  let active = true;
  const res = promise.then(
      value => active ? value : new Promise(Function.prototype),
      reason => active ? reason : new Promise(Function.prototype)
    )
  res.thrash = () => {active = false}
  return res
}
```

`Function.prototype` is a noop by spec, so we don't have to allocate one ourselves.

**Comment by hjylewis** [comment]
Hey! Thanks for posting this!

I've already commented on this [here](https://github.com/facebook/react/issues/5465#issuecomment-343467025) but let me know if you need help seeing why this doesn't allow for Garbage Collection.

You can clone this repo and replace `src/index.js` with your implementation, and you should be able to run `npm test`.  Make sure you fix the `thrash -> trash` typo first too.

**Comment by pygy** [comment]
I can't get the GC test to pass, but running that code in a loop doesn't leak indefinitely either. The memory consumption plateaus at ~1.5GB here in Node, and ~5GB in Firefox. There's a runaway leak in Safari though, I had to kill it at 10GB.

The thing is, it doesn't have to leak. Using the Mithril Promise polyfill (which is A+ compliant), the [memory usage is low and steady](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHggAIIATAXgB0QAIygQ0AawEA+AEIsA9BEkgAvhXTZciEAAUATrSwQ4MbbSgBPSFCj4AVgip0GTYngBuGXez0GjJs5bQUOw87GAArmjUxBD0ABQwAB4w1OHEtLoAlOzAfGh8MWDscQCEccSERpxocMQYUTC0RT6GxqYWVlCZ2RX6AO7saDADAKK6+rpxAi1+7FjhteyCMOzUGNYwXOx9EBXsAAZDffsCmXkFEEXl5gAOjUVJKWkZ7CU8oQIRUTH0p+y9tAGR3YABVbjAxhMpiBHql0l55otluwMGFItFYvkQGd8vliB4vMYoEVQhUjBR2Lp4GY3DBdHAQuxkABdClU2wpeEM0IstnUqC0gDC4XGLkZhHqXFgkypcBpdLgFOIunCMEyfI50WFooY4sl0ri7M5GUVYXWxhxBQJ1Vq9WoK1CRLA+AA+qJbQ1GcBZfL6YhKfzafSNca-QHNVzlOd8Z5VusoABBODmKKM4jgprsYzEACSWBwXAgGEYIXe7E+6J+WPYAH4szBc-nNkWS-7syCIDhaGlo18MfR2BK0FK6XERLUKXBCN2oFwE4I5bpBNlcniClTiCK0Gjvpj2LC0jA4h4oKqV9GClbYxUmBfiAVleYcnfL4VilOZ3OFxlBOwAGR-uwJ6qq8oRoOE1j-oB1x3JmwEOmWAi0IIEYCOwAA+6H-BmRTwaWHzgJWmJ-AB2GwVcN7bqE8H4JR2TvARfZVn8q6vmxb7HusIEMfWxI9IQ-SDMMoLgpCGTQjMxhxmgADkxBLCsPoCps2xyJwxBOqcL73jpB6MAA8g05SEEw+CCKIXCcaeaqWjpr5RmudmMFAUmsU5r5rNYSYptQcRMZicTno57EXFcJQfhBX6Lr+pHjsQ+CwGgADmew8QADNkThyrA+B0lC0y0HAcAQMIKyREOI5bDc+itIpMARpiiACBS8G2SFOlgC8nFeBwoRpQA3Jw7AsOwcUJUwKWEINEAANQzdkcXIBAzJWWe2nsUpQZwONyWpewaUhtEJo7ZNjJpetTnunUDT4LaJaOtOkXztFF2vlddowPgG66E+oT+fEK56UerUOe1BTKG1Tmg1D2lrMQ1CEMUarPsFOlGlqIpUgwCSQ+Dd7Q9D-3bkDhn2sZTBBa+1oqjUZ13kTlKRH5aCU05G5bju-ZoKtyNuexlzFDTcBzewkj7dk7O6Li7VgNzrXadDeOOda9B5S8oQ04a9WctqWPEJDj45JRhpM5tMC6y46rsKr4wZJkyhxvDiM4zkNtQmqBPnHiJNGXpdt5A5kn+B0QT4NVtDpOmdy0SZVGc1WcT0AAYhBnSbBS9AAEra1zrPWk6aaVKa72eo6MDEq6Jf2r2REDhVsBxJ5UCCBg1BiBScUUkMiTEJOdSMKzBRjTcCyEH5tdy1xvPaQLMH3HG1gt23oGMRPfzd8QPO485UmG96gYwAAckkm9N0vYhb-bjsI0jK6z+jxDHz3Es54-J844rxAQ3es9R-PVefW+r9RChFdy-BAFBLM-cEKhAAbdaB2Q4FAMCtGaG1MD5P17uGTkmDozWnDrVRkwIg7tECNYceYDuZm0OvrHIZtMGMmodg6IDCNav2-nieuR5k6pyCOnG0117RfQPsGAM2VaSYKVCqNUFIuGJzQNnBq9AKRINfiaGhkizQuTVNGSW24CF+ADnkEhAROhh30JHcE+A4Y3z+hPeRijOSYlZno-4RcY5MDiOBawGcFGv2cUYtAJiQ7WGEeIh08cAqtRRqFYoeEAGZmCWQroAZNxSyAlPXRDYObEJqn4UhnQKFcy1uElcZst4cMDnktopjQ4P0ZETLeMTlTZPSbk3wNSQlQCKQnJhD8ymvwqTiKpHTg7JPwPGBp9i4ouNadudptUClBB6QFPpr9B4xi8JHdYjIxqJUmhSOgkR5J9RalPbkTJmQ-yuHsiaqUywZTEfKOILJIblykp1Lw3Uhp9WmsNUaRh4r7IqNNOaGyCgrPiBAcFHUJ6rHoHAcIOAml83cvDbsDA5qvRjNZOAS1mSMngti2eRzdQ8W2Sk8p8E4DbyVu1Wei1lqgUGBBYIpE56ZkZQSniSEUKcjQphMi88uX4XLKArmJFAJ-05YC-FHiqIgKJixbFXL5WNwRUimANDaVfwuu8lYWVNVjllctbeEM4jQvxqg4ZxjqljLMboVuETGkzOaa4hZ+TankMaWsiMGzPlxNjL1fafyRq3N2lNTgYLmmvlVcbX1nJIYExtbiFQagQCYBwHgOwDgaD0EYMwLQDMsAYDEDAEEjqpwYFKnEAxFoUbsFGg2FEGJaRpmkf1PIjasryVlIyOtn1jZdsbRk6yIQxatxiG2useF-QeuMHEQK46cgQwoMOxtVIMByiomLVcI6R2z0nRAWkQV937oBAMTd27O3bjPQ7fVDaz0brmUJAYQdF30V3RDG9T6HL7r-ewTIP6xG0UrYjUIS6eC7qPW2v65oYD9WUMB1xJSgOBLyNQKAW6GRJ1oLQR9PaVRHUmAO09I6yTbSSICi5ypVTAcbQO9dI61WQd3Ux-dcg1I5hRFgQcZhCzJWtgwfDFGAxgDpEwIR+B8DsfI+4s27a6OyY4U+6xxYEYfuXXup97BOPsG49gPjs5RBJSE+kNxVQqTiaxlJmTt6n0UeERGRTCHlNodvQ5UGaAGaazI-gu1RDhLvoU1Bx9ja9MAAl+MMnzfhqzEnPSZgU2fVuEh7P1mIB2LsaQSnygpAARjSkV9zjbv3DutMqLdEpSpB0ZCWstFaqvVobqR4Den9J8uiNsFYfR6jySSp4FuSUVJ0A2NETY5XYydXw2BYSuHaDlDA81kwdqSu6bUoKD6UA5CVanOwAdClPl1XCXAYdu3quwCDqBqrgVgNXfKZkNVNMU15B2MOQE+BauhCSZ0PInHfNpvUFmrQ1iiqUDzc4QtIAVDMmUEAA) (uncomment the `run()` call at the bottom). It looks like there's something fishy in the native Promise implementations.

Even with the polyfill, your GC test doesn't pass, no idea why. 

All in all, given the current Promise implementations your approach is far superior.

----

Regarding rejection, the onreject handler must throw the reason, not return it:

```JS
function makeTrashable(promise: Promise<*>): TrashablePromise {
  let active = true;
  const res:any = promise.then(
    value => active ? value : new Promise(() => {}),
    reason => {
      if (active) {
        throw reason;
      } else {
        return new Promise(() => {});
      }
    }
  );
  res.trash = () => {active = false;};
  return (res: TrashablePromise);
}
```

Also, Flow seems unaware that the Function prototype is callable but hey ¯\\\_(ツ)_/¯
