### ISSUE TITLE
Error: Couldn't find preset "es2015" relative to directory "node_modules/trashable"

### ISSUE THREAD

**Issue by shredder-rull** [hjylewis/trashable#9]
Is there a way to use it with React Native?

Versions:
Trashable: 1.0.6
React: 16.3.1
React Native: 0.55.1

Thanks!

**Comment by hjylewis** [comment]
I've never tried but my gut says it should work just fine with React Native.

That error seems to be related to `babel` which is only used during development.

How did you install `trashable`?

**Comment by shredder-rull** [comment]
yarn add trashable
I've tried to reinstall all node_modules but it didn't help

**Comment by hjylewis** [comment]
Are you see the error when? When you install?

**Comment by shredder-rull** [comment]
When launch the app by 'react-native run-ios'

**Comment by shredder-rull** [comment]
UPD: It works if I remove node_modules/trashable/.babelrc. May be needs add it to .npmignore?

**Comment by hjylewis** [comment]
That works! Do you mind making a PR?

**Comment by shredder-rull** [comment]
I've made PR. Please, let me know, when you update package. Thanks!

**Comment by hjylewis** [comment]
Try [1.0.7](https://github.com/hjylewis/trashable/releases/tag/v1.0.7). Let me know if that doesn't work.
